name             "remote_syslog2"
maintainer       "Barry Hoggard"
maintainer_email "barry@tristanmedia.com"
license          "Apache 2.0"
description      "Chef cookbook to install remote_syslog2 into /usr/local/bin from a release tar.gz file"
version          "0.1.0"
