name             "remote_syslog2"
maintainer       "Mike Taylor"
maintainer_email "mike@kitcrm.com"
license          "Apache 2.0"
description      "Chef cookbook to install remote_syslog2 into /usr/local/bin from a release tar.gz file"
version          "0.0.1"
